# Generated by Django 4.2.16 on 2024-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('task', models.TextField(verbose_name='Description')),
                ('city', models.CharField(choices=[('Almaty', 'Almaty'), ('Astana', 'Astana'), ('Shymkent', 'Shymkent'), ('Karaganda', 'Karaganda'), ('Taldykorgan', 'Taldykorgan'), ('Pavlodar', 'Pavlodar'), ('Semey', 'Semey'), ('Aktobe', 'Aktobe'), ('Ural', 'Ural'), ('Kokshetau', 'Kokshetau'), ('Petropavlovsk', 'Petropavlovsk'), ('Turkistan', 'Turkistan'), ('Aktau', 'Aktau'), ('Taraz', 'Taraz'), ('Kyzylorda', 'Kyzylorda'), ('Zhezkazgan', 'Zhezkazgan'), ('Kostanay', 'Kostanay'), ('Ekibastuz', 'Ekibastuz'), ('Balkhash', 'Balkhash'), ('Zalynsk', 'Zalynsk'), ('Esik', 'Esik'), ('Sergeli', 'Sergeli'), ('Zhanaozen', 'Zhanaozen'), ('Kandagat', 'Kandagat'), ('Shalkar', 'Shalkar'), ('Koktal', 'Koktal'), ('Yassy', 'Yassy'), ('Khromtau', 'Khromtau'), ('Nurin', 'Nurin')], max_length=100, verbose_name='City')),
                ('price', models.CharField(max_length=300, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
