# Generated by Django 4.2.16 on 2024-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_jobs_price_resume_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_description',
            field=models.TextField(default='Описание компании отсутствует'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='contact_email',
            field=models.EmailField(default='Default email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='contact_phone',
            field=models.CharField(default='Default number', max_length=20),
            preserve_default=False,
        ),
    ]
