# Generated by Django 4.2.16 on 2024-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='city',
            field=models.CharField(choices=[('', 'Выберите город'), ('Almaty', 'Almaty'), ('Astana', 'Astana'), ('Shymkent', 'Shymkent'), ('Karaganda', 'Karaganda'), ('Taldykorgan', 'Taldykorgan'), ('Pavlodar', 'Pavlodar'), ('Semey', 'Semey'), ('Aktobe', 'Aktobe'), ('Ural', 'Ural'), ('Kokshetau', 'Kokshetau'), ('Petropavlovsk', 'Petropavlovsk'), ('Turkistan', 'Turkistan'), ('Aktau', 'Aktau'), ('Taraz', 'Taraz'), ('Kyzylorda', 'Kyzylorda'), ('Zhezkazgan', 'Zhezkazgan'), ('Kostanay', 'Kostanay'), ('Ekibastuz', 'Ekibastuz'), ('Balkhash', 'Balkhash'), ('Zalynsk', 'Zalynsk'), ('Esik', 'Esik'), ('Sergeli', 'Sergeli'), ('Zhanaozen', 'Zhanaozen'), ('Kandagat', 'Kandagat'), ('Shalkar', 'Shalkar'), ('Koktal', 'Koktal'), ('Yassy', 'Yassy'), ('Khromtau', 'Khromtau'), ('Nurin', 'Nurin')], max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_description',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'worker'), name='unique_job_worker_application'),
        ),
    ]
