# Generated by Django 4.2.16 on 2024-12-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_jobs_city_alter_jobs_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='portfolio',
        ),
    ]
